---
# tasks file for plumelo.sentry
- include: install.yml
  tags: [sentry, sentry-install]

- include: postgres.yml
  tags: [sentry, sentry-database]
  when: sentry_db_engine == 'sentry.db.postgres' and sentry_db_install
  
- include: redis.yml
  tags: [sentry, sentry-redis]
  when:  sentry_redis_install
  
- include: sentry.yml
  tags: [sentry]

- include: services.yml
  tags: [sentry, sentry-services]
