---

# tasks file for plumelo.sentry
- import_tasks: install.yml
  tags: [sentry, sentry-install]

- import_tasks: postgres.yml
  tags: [sentry, sentry-database]
  when: sentry_db_engine == 'sentry.db.postgres' and sentry_db_install

- import_tasks: redis.yml
  tags: [sentry, sentry-redis]
  when: sentry_redis_install

- import_tasks: sentry.yml
  tags: [sentry]

- import_tasks: services.yml
  tags: [sentry, sentry-services]
